import "../globals.css";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { type ReactNode } from "react";

import { Locale } from "@/features/internationalization/i18n-config";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Next Starter",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
  params: { lang },
}: Readonly<{
  children: ReactNode;
  params: { lang: Locale };
}>) => {
  return (
    <html lang={lang}>
      <body className={`${inter.variable} antialiased`}>{children}</body>
    </html>
  );
};

export default RootLayout;
